### ISSUE TITLE
2 instances

### ISSUE THREAD

**Issue by golku1** [Stratehm/stratum-proxy#104]
is it possible to run the proxy 2 times ?

so i can separate the hashing speed to 2 different coins/algo's

**Comment by golku1** [comment]
i am running windows

**Comment by nukepower** [comment]
it is Possible i have done it with this proxy on the same PI , use two different folders but it may or may not have issue depending how strong the PI is, it's better using two PI's. if you can . unless it's a full PC then it shouldn't be a problem on a PC that can run win 10 an you should be able to handle a few instances at once with Ubuntu or what ever OS you use .:) ....

2 different coins/algo's i never tired but did read on the bittalk forums were some one posted a Script that could do it ..a while back .like may be a year or more ago .

**Comment by golku1** [comment]
i did try to make 2 different folders
but couldn't find a way to edit the port's

**Comment by nukepower** [comment]
Ive nevr used it on windows Linux was easyer to setup for me and im a windows user but look in the 
stratum-proxy-full-sample.conf file  in the stratum-proxy-0.8.1/folders or in your named folders 
and change the 
"apiListenPort" : 8888, port to lets say 8881 or some thing like that or 

"apiListenPort" : 8881, 

with the quotes...  to different ports in each folder .

that should let two load at once on the same PC if it doesn't play with these two settings
"getworkListenPort" : 8332,
"stratumListenPort" : 3333,

those two setting shouldn't matter, the one that does is the api Listen Port
and then to see the UI 
access it some thing like this at any browser on your local home network.

http://192.168.1.206:8881
http://192.168.1.206:8888

and to join whatever instances you want something like this 

stratum+tcp://192.168.1.206:3333 
stratum+tcp://192.168.1.206:3332 

you may need to change out the stratum port to the proxy  or  play with those 3 settings  till you find the 
ports that work and kind of why it's better on two PI's over one or even two mini PC running windows .
and if you watch the black screen once you get it to load 2 instances on the same PC it tells what ports it's listening on.
I haven't used this for months so i had to think for a bit what i did .

**Comment by golku1** [comment]
Thanks ! it worked changed the ports and now the stratum proxy is working fine
only I cant get in the interface but that isn't a big problem
