### ISSUE TITLE
package HEAD - no webui?

### ISSUE THREAD

**Issue by meoso** [Stratehm/stratum-proxy#26]
I performed `mvn clean package` to produce stratum-proxy-0.6.0-SNAPSHOT.jar, but launching it with the same exact parameters as for v0.5.1 results in no webui.  at first i thought it was not listening on port 8000, but if i hit it immediately, it shows a webui without graphs, then the listener crashes (i suppose) and then no listener exists. (but the proxy still runs)
```
#proxy=/home/username/coin/Stratehm/stratum-proxy-0.5.1/stratum-proxy.jar
proxy=/home/username/coin/Stratehm/stratum-proxy/target/stratum-proxy-0.6.0-SNAPSHOT.jar

echo "Starting proxy"
screen -S proxy -d -m /usr/bin/nice java -jar "${proxy}" \
--scrypt --stratum-listen-port 3334 --getwork-listen-port 8334 --no-midstate --api-listen-port 8000 --rest-listen-port 8000 \
--pool-hosts multi.ghash.io:3333 freedom.wemineltc.com:3339  \
--pool-users username.x username.x \
--pool-passwords x x
```

```
$ java -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
```

```
$ node --version
v0.10.29
```

**Comment by Stratehm** [comment]
No error during the maven build ? (sometimes, the build is SUCCESSFUL but there is an error when building the webapp and so it is not available).

What kind of error do you have in your browser ? Blank page, 404 or 503 error, ... ? 

PS: You should use  only --api-listen-port 8000 and remove --rest-listen-port 8000. It is just an alias of the same parameter.

**Comment by meoso** [comment]
no server code, just `Problem loading page`
```
Unable to connect
Iceweasel can't establish a connection to the server at 127.0.0.1:8000.
```
mvn output: http://pastebin.com/PEU8tvxk

removed --rest-listen-port as recommended.

at first `netstat -tp | grep 8000` shows the listener, but after a few moments it shows nothing

**Comment by Stratehm** [comment]
Could you send me the stratum-proxy.log file which should be int your /tmp directory ?

Thanks

**Comment by meoso** [comment]
https://mega.co.nz/#!Lo0XQYTB!tm0Bx4b_y11e3uUHl3orz4Q6J1EHfOe7TOv2_DLgbUs

**Comment by Stratehm** [comment]
I see severals errors of this kind:
2015-01-23 09:22:18,958 WARN  [main]: [Launcher]    lib/stratum-proxy-webapp.jar not found. GUI will not be available.

I think you are running the proxy directly from the target directory after the maven build. The GUI is not available when the proxy is run from this directory.
To work properly, you have to unzip the whole ZIP file in a directory and run the unzipped stratum-proxy.jar

**Comment by meoso** [comment]
that was indeed the issue.  i apologize for not understanding the proper methods of build/deployment.  thank you!

**Comment by Stratehm** [comment]
No problem.
