### ISSUE TITLE
Windows Web GUI Not coming up

### ISSUE THREAD

**Issue by kieths** [Stratehm/stratum-proxy#29]
Running the Windows JAR, but it appears that only the Grizzly framework and various file reads shows up, not the standard interface (seems ok under Ubuntu after compiling, for comparison, just not on Windows).  Missing files?  0.6.0..

**Comment by kieths** [comment]
Internal Server Error
Jar file was not found

     1: org.glassfish.grizzly.http.server.CLStaticHttpHandler.getJarFile(CLStaticHttpHandler.java:349)
     2: org.glassfish.grizzly.http.server.CLStaticHttpHandler.handle(CLStaticHttpHandler.java:288)
     3: strat.mining.stratum.proxy.grizzly.CLStaticHttpHandlerWithIndexSupport.handle(CLStaticHttpHandlerWithIndexSupport.java:60)
     4: org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:188)
     5: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:219)
     6: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
     7: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
     8: java.lang.Thread.run(Unknown Source)

Please see the log for more detail.
Grizzly 2.3.16

**Comment by Stratehm** [comment]
This problem is rare but I have no workaround.
I will modify the way the WebApp is packaged with the proxy. It will solve this problem.

**Comment by kieths** [comment]
Thank you very much!  Will try the update when available.

**Comment by Stratehm** [comment]
Finally, I have not modified the WebApp packaging, but only the way the WebApp is accessed.

**Comment by jjziets** [comment]
I found the same bug in the windows release. stratum-proxy-0.8.1.zip 

Should I compile from the source?
