### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by SoonCoin** [Stratehm/stratum-proxy#31]
Is there a way to open multiple instances of the proxy?
i mean i  want 1 running on sha at port 12345 and 1 for scrypt at 22345
i tried to run is with dif configs but giving errors trying to start 2nd 1.

**Comment by Stratehm** [comment]
You have to modify several parameters to run several instances on the same host.
stratumListenPort, getworkListenPort and apiListenPort have to be different for all instances. If you do not need some of these ports, you can disable them with respectively disableLogAppend, disableStratum and disableGetwork.

You also have to specify a databaseDirectory for all instances.

You should also set logDirectory (even if not mandatory).
