### ISSUE TITLE
Difficulty per miner

### ISSUE THREAD

**Issue by sburina** [Stratehm/stratum-proxy#33]
Hello!

I have two miners connected to the same vardiff pool via stratum-proxy. One is 1 Th/s, another 15 Gh/s. The stratum proxy is configured to append the worker names to the common username, so both workers are visible on the pool, and one would expect they should be treated completely separately. The pool tries to assign different difficulties to each worker, but it seems to me that stratum-proxy broadcasts the diff change to all connected miners, so both of them pick it up as soon as they happen. I was unable to get the stable and properly different difficulties for two very different miners even in the longer run.

Is this something that could be fixed in the stratum-proxy code, or the problem is burried somewhere in the protocol itself?

Thank you!

**Comment by Stratehm** [comment]
It is indeed a limitation of the stratum protocol. Stratum was not really designed to support proxyfying. The proxy open only one connection to the pool and multiplexes several worker connection on this pool connection. This leads to set_difficulty notification conflicts when vardiff is enabled per worker on the pool.

The solution could be to open several pool connections  (one by worker), but it needs an heavy refactoring (and I have not enough time). I remember someone has started a new stratum proxy which behave like that (one pool connection by worker). He posted about his proxy on BitcoinTalk on the thread of this proxy several months ago. I do not remember his name and if his proxy is open source, but maybe you could contact him.
