### ISSUE TITLE
Request API - GET Summary Command

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#35]
Request API GET summary command which lists the following  (similar to cgminer/cpuminer/bfgminer)

-total current hash
-total accepted
-total rejected
-total errors
-total total elapsed time (connected to pool)
-current pool name

This command would automatically be run against the current active pool

**Comment by Stratehm** [comment]
Added

**Comment by computeronix** [comment]
?Sweet!!  Thank you!!  I will try it out


Bill McIlhargey
317.315.3869
bill@mcilhargey.com
________________________________
