### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#37]
add the ability to grant users to certain sections and grant the ability for read/write access to pool and other settings

**Comment by Stratehm** [comment]
This feature will not be implemented. The proxy was designed to run in a trustful environment. No rights and users management is needed (except of course the authorization to access the WebUI from Internet)

**Comment by computeronix** [comment]
Gotcha. Fair enough

Sent from my iPhone

On Apr 1, 2015, at 5:20 PM, Stratehm <notifications@github.com<mailto:notifications@github.com>> wrote:


This feature will not be implemented. The proxy was designed to run in a trustful environment. No rights and users management is needed (except of course the authorization to access the WebUI from Internet)

-
