### ISSUE TITLE
The location of stratum-proxy-webapp.jar

### ISSUE THREAD

**Issue by leacoin** [Stratehm/stratum-proxy#38]
Hi!

Every time I compile stratum-proxy from scratch somewhere, I need to manually symlink the file target/stratum-proxy-webapp.jar to target//lib/stratum-proxy-webapp.jar, otherwise there's no web interface. Is this on purpose or am I missing something? :)

Thank you!

**Comment by Stratehm** [comment]
It should be fixed.
