### ISSUE TITLE
Lowering of the nonce value

### ISSUE THREAD

**Issue by ARandombitcoinuser** [Stratehm/stratum-proxy#39]
Hi,

First of all thank you for all the amazing program and the hard work you've put into it.

I'm currently having an issue with using this proxy because it lowers the nonce value on the miners side. My new hardware needs a nonce value of at least 4, but since a lot of pools have a nonce value of 4 after running the proxy it gets cut back to 3, which is too low for new hardware. Is there any way to run the proxy without cutting the nonce value? It'll only be one worker per proxy regardless if that's the only way.

Thanks in advance.

**Comment by Stratehm** [comment]
The commit c051341f566 has added the value 1 to the nbWorkerLimit option. You can set this value to the option in your configuration file/command line.

**Comment by ARandombitcoinuser** [comment]
Awesome, thank!

**Comment by ARandombitcoinuser** [comment]
Edit; Trying to compile but having difficulties, could you compile the version with the new commit for me? Will send a donation :)

**Comment by Stratehm** [comment]
Done.

Thank you for your donations!
Cheers

**Comment by ARandombitcoinuser** [comment]
Works perfectly, donated!
