### ISSUE TITLE
Extranonce Between Miners and Proxy

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#41]
Is it necessary or recommended to add the #xnsub to the end of the stratum url for the connection between the miners and the proxy? Is this not needed/supported?  Extranonce is enabled from the proxy to the pool in my configuration.

**Comment by Stratehm** [comment]
The  #xxxx parameters at the end of a pool URL is software specific. I think only BFGMiner uses this syntax.
When your workers are connected to the proxy, you should always activate the Extranonce subscription.

On the pool side, it depends if the pool support the Extranonce subscription. But even if the pool does not support this feature, it should not hurt the connection if you turn it on (it will simply be ignored, but some pool may break the connection, just try).
