### ISSUE TITLE
don't support "_" in pool host got null error

### ISSUE THREAD

**Issue by captminer** [Stratehm/stratum-proxy#43]
hi pfool, looks like proxy does not support an underscore "_" in the pool host name & showed a null error. appreciate if it can be fixed asap.

many thx. 

eg : stratum+tcp://stratum_xxx.xxx.com:3333

**Comment by Stratehm** [comment]
Java does not allow underscore characters in hostnames. Underscores are illegal in hostnames (RFC 952, RFC 1123), even if many browsers and Microsoft's OS accept them. 

I cannot do anything.

**Comment by captminer** [comment]
ouch, that hurts ... will try to figure out another way then. many thx for the prompt reply :)

**Comment by Stratehm** [comment]
Maybe you could use directly the IP address ine the URL instead of the hostname.
Try to use the following command in a terminal to translate the name to an IP:
nslookup stratum_xxx.xxx.com

**Comment by captminer** [comment]
it worked mate, thx so much for reminding me.
