### ISSUE TITLE
miningrigrentals.com

### ISSUE THREAD

**Issue by GordonChou** [Stratehm/stratum-proxy#44]
I think this is the best stratum proxy server on earth but why I can't point my rigs to miningrigrentals? 
It always says trying to reconnect and suggest difficulty, but my rigs can mining at miningrigrentals with out any problems.Maybe it's just a little bug of the server, will be very appreciate if you can fix it in next release:)

**Comment by Stratehm** [comment]
Could you send me the proxy log file when the problem happens ?

Thanks

**Comment by stewie0056** [comment]
Gordon,

I experienced what you were describing with miningrigrentals.com.
the solution was to not suggest a difficulty in the conf.
works perfectly now.

Stratehm,

Could you provide a solution for suggesting a difficulty on mingrigrentals.com?
It would be nice to do but im not sure if its compatible with them.

Thanks!

**Comment by Stratehm** [comment]
I do not know any other solution to suggest the difficulty to the pool except the one already implemented in the proxy. 
If miningrigrentals.com reject the connection because of the difficulty suggestion, unfortunately, there is nothing I can do.
