### ISSUE TITLE
[Question] KNC Titan skipcbcheck

### ISSUE THREAD

**Issue by computeronix** [Stratehm/stratum-proxy#49]
Does the stratum proxy support skipcbcheck inbound to the proxy and from the proxy to the pool?

https://www.westhash.com/?p=asic / nice hash recommends to useskipcbcheck as part of the command line to connect to the pool
KnC Titan: stratum+tcp://stratum.nicehash.com/#xnsub#skipcbcheck

BFGminer now supports this and I am curious if the proxy supports this?

**Comment by Stratehm** [comment]
I do not really know what is the aim of this option on BFGminer but it seems not to be related to the stratum protocol. So this option should be transparent for the proxy.
