### ISSUE TITLE
cgminer 4.9.1+ set 0 difficulty

### ISSUE THREAD

**Issue by cytener2** [Stratehm/stratum-proxy#51]
When trying connect cgminer 4.9.1+ (kanoi) to proxy got message like
Pool 0 set difficulty 0
as a result all hashpower rejected by pool.
proxy pointing to antpool or bitcoindigger - same results.
when i using slush0 proxy - all working fine on both pools.

**Comment by Stratehm** [comment]
Which algorithm are you mining on (Scrypt, SHA-256, X11,...) ?

**Comment by cytener2** [comment]
sha256 (bitcoin)

**Comment by Stratehm** [comment]
Do you have the same problem with other versions of cgminer ? Could you post your proxy configuration ?

**Comment by cytener2** [comment]
no. cgminer/3.9.0 working fine

**Comment by Stratehm** [comment]
I will need the log file with a DEBUG loglevel. Thanks.

**Comment by cytener2** [comment]
I just prepare it. You can download log at http://wikisend.com/download/467066/debug.log.gz

**Comment by Stratehm** [comment]
I do not know what is the problem. The proxy sends correctly the difficulty to the miner. For example:
2015-06-06 03:54:22,819 DEBUG    [/xxxx:56588-Thread]:strat.mining.stratum.proxy.network.StratumConnection - /xxxx:56588. Send notification: {"id": null, "method": "mining.set_difficulty", "params": [1024.0]}

But indeed, your miner sends low difficulty shares to the proxy which are rejected by the pool. I do not see what I could do. 
Have you tryed to connect your miner directly on a pool ? If it works, could you send me a packet capture of the traffic between your miner and the pool (with tcpdump or wireshark) to look at the differences when the proxy is involved ?

**Comment by cytener2** [comment]
Hi. I'm confused. While i recording tcpdump from pool, after about 3minutes i see 'Pool 3 set difficulty 0' .
Now, i think cgminer involved? I can share dump only after weeked.

**Comment by Stratehm** [comment]
Sincerly, I think it is a cgminer issue, but I will take a look at your dump if you want.

**Comment by cytener2** [comment]
After some more playng with this cgminer I came to the conclusion: he work fine on 1024x difficulties, e.g. 1024, 2048, 4096 etc. Maybe 256, 512 too. If pool set other digits, cgminer assume it as 0.

**Comment by Stratehm** [comment]
OK, closing the bug.

Thank you for the feedback.
