### ISSUE TITLE
Extranonce2 size is 3 : Nicehash won't work.

### ISSUE THREAD

**Issue by a1binos** [Stratehm/stratum-proxy#52]
Hi!
Is there a chance to modify this setting? Extranonce2 size is 3. I can't connect rented nicehash power, because of this Extranonce2 size is 3. Nicehash will work with only Extranonce2 size is 4.

**Comment by Stratehm** [comment]
If you expect to have only one miner connection on the proxy, you can set this option in your configuration:
"workerNumberLimit": 1

It means that only one miner can connect on the proxy but the extranonce2 size is not modified.

Default value is 256. It allows 256 miners to connect on the proxy but substract 1 to the size of extranonce2.
