### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by sburina** [Stratehm/stratum-proxy#53]
Hi!

Can you please consider formatting the numbers in the web interface, so
"Accepted hashrate 967570232442"
gets at least some commas and dots, and maybe even some prefixes (K,M,G,T,P) with numbers divided  appropriately? Maybe even make it configurable? :)

Thank you!

**Comment by Stratehm** [comment]
Done: commit 1da38ddd51

**Comment by sburina** [comment]
Hi!

Cloned, compiled, and I can't see the difference. Could it be it's dependent on some i18n stuff I don't have installed?

**Comment by Stratehm** [comment]
Try to refresh/clear your browser cache. Hit Ctrl+F5 to reload the page without cache or Ctrl+Shift+Del to clear all the cache.

**Comment by sburina** [comment]
Gosh, that was it! It works, thanks a lot! :)
