### ISSUE TITLE
Unknown request type warning

### ISSUE THREAD

**Issue by vanch** [Stratehm/stratum-proxy#54]
Hello.

I'm using bfgminer v3.8.1 with stratum-proxy v0.8.0 using stratum+tcp protocol between them.

Everything seems ok, but I can't find anything about one warning appearing for semotimes in proxy log.
```
2015-07-15 13:36:57,468 WARN     [10.12.6.44-Thread]:strat.mining.stratum.proxy.network.StratumConnection - Unknown request type on connection 10.12.6.44. methodName: mining.get_transactions, id: txlistBQCHARS, params: [BQ391uVCHARS]
```
It seems like this request (get_transactions) is initiated by bfgminer for proxy healthchecks. Maybe I'm wrong.

Can you, please, disperse my doubts about this is an error, bug or something non-working.

Many thanks.

**Comment by sburina** [comment]
Hi!

As far as I know, this is benign, you can ignore that error.
You can also try adding "#skipcbcheck" to the end of your stratum URL in bfgminer configuration, it could stop bfgminer from sending this request.

**Comment by Stratehm** [comment]
Thanks this solution sburina.

The proxy now replies an unsupported operation error when it receives a mining.get_transactions request.

**Comment by Stratehm** [comment]
commit fee90448fbb12

**Comment by vanch** [comment]
Well, #skipcbcheck won't work. And now it's error instead of warning. Can you turn me why this message being send to proxy?

**Comment by vanch** [comment]
Anyway, now I'm getting megabytes of logs with no ability to turn them off.

**Comment by Stratehm** [comment]
You can modify the log verbosity by modifying the logLevel option in your config file to one of the following values (by increasing verbosity order):
OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE

**Comment by vanch** [comment]
I still want to see all errors I have. That's not an option.
