### ISSUE TITLE
Can connect antminer S3 to the stratum-proxy?

### ISSUE THREAD

**Issue by prr0** [Stratehm/stratum-proxy#59]
HI,

I just configure a stratum-proxy on a RPI and am trying to connect my antminers S3 to the proxy but appear dead on the miner

I put http://proxy_IP:8332, what I missing?

Thanks in advance

**Comment by Stratehm** [comment]
Do you want to use Getwork or stratum protocol for mining ? http://proxy_IP:8332 is for Getwork. If you want to use Getwork and it does not work, I will need the proxy log file to check if it is a proxy issue.

**Comment by prr0** [comment]
Thank you Stratehm, I'll activate the log, am trying to control several miners at one time, in the nicehash I read that I have to use getwork and the proxy to do that

I'll activate the log with error option and let you know if there any message there

**Comment by prr0** [comment]
Stratehm just a question, I put my wallet and password on the .conf file, but what I need to put in the miner configuration page, maybe the error is there, I put the wallet and the password again

**Comment by Tomcatt** [comment]
The user name and password doesn't matter when connecting to the proxy server.

**Comment by Stratehm** [comment]
In the proxy conf file, you have to put your BTC address on which Nicehash will send you the mined funds as login and any value as password. Then on your miner configuration, you can effectively put any values you want as login/password.

The proxy accepts all the connection and does not check this values (the login is only used to differenciate users on the proxy Users page on the GUI)

At the moment, you have set login/password of your Nicehash wallet in the proxy conf file, right ? If so, I recommand you to change your Nicehash wallet password immediatly, since it has been sent to Nicehash with the stratum protocol which absolutly not secure.

**Comment by prr0** [comment]
NO, in the .conf file I put the wallet address I use in nicehash and any password, then on the miner I put the same wallet address and any password, no the login/password of nicehash

but still no connection of the miner with the proxy, keep said dead

**Comment by prr0** [comment]
This is part of my .conf file, did you see something wrong?

  "logDirectory" : "/opt/stratum-proxy/logs",
  "logLevel" : "ERROR",
  "getworkListenPort" : 8331,
  "getworkListenAddress" : "0.0.0.0",
  "disableGetwork": false,
  "apiListenPort" : 8888,
  "apiListenAddress" : "192.168.0.107",
  "databaseDirectory": "database1",
  "isScrypt" : false,
  "disableStratum" : true,
  "pools" :

and this is the Pool part con the .conf file

"name" : "Nicehash US",
    "host" : "sha256.usa.nicehash.com:3334",
    "user" : "MY_WALLET_ADDRESS",
    "password" : "x",
    "enableExtranonceSubscribe" : true

**Comment by prr0** [comment]
I saw this on the log file

2015-09-27 10:43:33,374 ERROR [Pool-Nicehash US-Thread]: [Pool]    Disconnection of pool Pool [name=Nicehash US, host=sha256.usa.nicehash.com:3334, username=MY_WALLET_ADDRESS, password=x, readySince=Sun Sep 27 10:36:36 VET 2015, isReady=true, isEnabled=true, isStable=true, priority=0, weight=1].
java.io.EOFException: Connection closed.
	at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:166)
2015-09-27 10:43:33,380 ERROR [Pool-Nicehash UE-Thread]: [Pool]    Disconnection of pool Pool [name=Nicehash UE, host=sha256.eu.nicehash.com:3334, username=MY_WALLET_ADDRESS, password=x, readySince=Sun Sep 27 10:36:36 VET 2015, isReady=true, isEnabled=true, isStable=true, priority=1, weight=1].
java.io.EOFException: Connection closed.
	at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:166)

**Comment by prr0** [comment]
do I have to change 

"stratumListenPort" : 3333, to "stratumListenPort" : 3334,?

**Comment by Stratehm** [comment]
-The Getwork port in the configuration file is 8331. In your first post, you have written this URL: http://proxy_IP:8332. It is not the same port.

-java.io.EOFException: Connection closed. This error typically happens when the connection is rejected by the pool. Could your run the proxy with a log level of DEBUG instead of ERROR ? We may see the cause of the disconnection.

-"stratumListenPort" is not useful in your case since you are using Getwork.

**Comment by prr0** [comment]
OK I will do it in debug mode, I recheck the proxy port and is 8331 in the config file and in the miner config

**Comment by prr0** [comment]
I try with a S5 and is working, still there is a desconnection but the pool appear alive in the S5 in the S3 still appear dead I will try in another S3 a let you know

**Comment by prr0** [comment]
work for a couple of minutes and then the miner lost connection with the proxy, can't send the log said 

Something went really wrong, and we can’t process that file.  Try again.

**Comment by prr0** [comment]
there's a place where I can upload the log file?

**Comment by prr0** [comment]
On he antminer S3 appear DEAD on the antminer S5 works for a 1 or 2 the goes DEAD

**Comment by Stratehm** [comment]
Any file transfer site is fine (https://filetea.me/ for example). Just post here the link to download the file.

**Comment by prr0** [comment]
HI Stratehm,

Again thanls for the time here the link t the logs file

https://www.dropbox.com/sh/whuumz2wt04pn33/AACx4HtvIQmXzM4dMmc4YoNPa?dl=0

**Comment by Stratehm** [comment]
I have not seen last time, but in the configuration file, the "isScrypt" option is false. To mine on the Scrypt algorithm, you have to turn this option to true.

I suppose that the miner with IP 192.168.0.51 is the S5. I do not see any other IP trying to connect on the proxy in the log, could you tell me the IP of the other miner (the S3) ?

**Comment by prr0** [comment]
HI,

The S3 never connect to the proxy appear DEAD, just the S5 connect to the proxy, I try to mine SHA256 that's why I put isScript to false

**Comment by Stratehm** [comment]
> I try to mine SHA256 that's why I put isScript to false

OK.

> The S3 never connect to the proxy appear DEAD, just the S5 connect to the proxy,

Yes, but you want the S3 to connect on the proxy. So we should at least see in the logs a connection attempt from it and eventually a rejection of this connection by the proxy. 
Since we do not since such connection attempts in the proxy log, maybe the S3 is not configured with the good proxy ip/port or you have a network issue (a bad firewall configuration for example). In this case, the S3 cannot reach the proxy and declares it as DEAD.

**Comment by prr0** [comment]
OK, I upload a new log file .log.290915 in this one I try with 3 S3 first (x.x.x.22, x.x.x.23, x.x.x.24), the proxy appear DEAD, them I try with a S4 (x.x.x.42) get connected but all work rejected and last and S5 (x.x.x.51) get connected all work rejected, all miners are connected to the same switch are on the same network and I copy&paste http://192.168.0.107:8331 on each miner

**Comment by Stratehm** [comment]
The link to the new log file in your comment is not complete.

**Comment by prr0** [comment]
Sorry Stratehm, the 192.168.0.107 is the address I copy and paste on the miners

This is the link to the files
https://www.dropbox.com/sh/whuumz2wt04pn33/AACx4HtvIQmXzM4dMmc4YoNPa?dl=0

**Comment by Stratehm** [comment]
In the new log file, I can see the S4 and S5 connections but there is still no connection from any S3. While there is no connection attempt of a S3 on the proxy, I will not be able to help you with this problem. Maybe you could make a TCP capture (with Wireshark or tcpdump) on  to check that the S3 actually send HTTP requests to the proxy.

For the rejected shares problem, I will need a new log file with the option "logRealShareDifficulty" to true in your configuration file.

**Comment by prr0** [comment]
OK perfect Stratehm I will send you the new log and don'tworry about the s3 I prefer you help me with the S5 and S4 issue

**Comment by lesjokolat** [comment]
Hi @prr0 I was wondering if I could ask for your help. I am looking at building a miner myself and wondered if you had a old log file I could review? I am interested in how the coinbases, merkle root are defined. Please anonymize anything you feel is a security risk. Thanks in advance.
