### ISSUE TITLE
Set Max Difficulty 

### ISSUE THREAD

**Issue by mcbiv** [Stratehm/stratum-proxy#60]
Hello,

   And Thanks for this great Java based stratum proxy server it works very well.
Although I was wondering if there is a way to set an overall maximum difficulty rating.
Or an individual max difficulty rate per user? Please let me know and again thank you

**Comment by Stratehm** [comment]
The proxy has not this kind of feature.

Theoretically (and with a lots of development), it should be possible to send a different difficulty from the pool one to workers. The limit is that the worker difficulty has to be lower or equals to the pool difficulty. If someone wants to make a Pull Request for this feature, he is welcome.
