### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by jeeweevee** [Stratehm/stratum-proxy#61]
Hi, 

I like the SSL option. Is it possible to use my own domain related SSL certificate and use port 443 if ssl is enabled?

Thanks!

**Comment by Stratehm** [comment]
I never tried but it should be possible.

You will have to replace the keystore generated by the proxy by a new one with the following constraints:
-The keystore has to be in JKS format (you can use the keytool utility available with the java JRE to convert your certificate and store it in the keystore, for example https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html)
-be located in the database directory 
-be named stratum-proxy-keystore.jks
-the alias of your certificate in the keystore as to be stratum-proxy
-the keystore password has to be stratum-proxy
