### ISSUE TITLE
Wrong accepted hash for lyra2rev2

### ISSUE THREAD

**Issue by coolinger** [Stratehm/stratum-proxy#62]
When using lyra2rev2 to nicehash the accepted hashrate is way off.  It shows about 50G when it is only 190M. Also the difficulty is way off.  Real 128 shown 20278476.371434607. 

Am I missing some configuration setting? 

Keep up the great work!

**Comment by Stratehm** [comment]
I will need the log file with a DEBUG level to check what happens.

**Comment by coolinger** [comment]
Hare is a log file over 10 minutes. In this time the Accepted Difficulty raised up until 2362.
At the end, Accepted Hashrate was at ~16G.

Thanks!
[stratum-proxy.log.txt](https://github.com/Stratehm/stratum-proxy/files/66394/stratum-proxy.log.txt)

**Comment by Stratehm** [comment]
Could you try the new beta-release (0.8.1-SNAPSHOT) adn configure the option "hashesPerShareDiff1Divider" with a value of 256 ?

**Comment by coolinger** [comment]
The hashrate seems ok (67,109  MH/s in proxy, 66.2140 in nicehash)
The difficulty is still wrong: 37.676 in proxy, 32.00000000 in nicehash.

I put the option inside the proxy configuration, not inside the pool configuration. Correct?

**Comment by Stratehm** [comment]
Yes, correct.

For the difficulty, unfortunately I do not see any problem in your log file.

> Also the difficulty is way off. Real 128 shown 20278476.371434607

You see 20278476 in the Web client of the proxy and 128 on the Nicehash website, right ? What is the difficulty reported by your miner ?

**Comment by coolinger** [comment]
At this very moment:

Proxy says:
Uptime: 2 Days
Accepted difficulty: 135.154
Rejected difficulty: 16
Accepted hashrate: 13,422 MH/s
Rejected hashrate: 0 H/s

Miner says:
NAME=ccminer
VER=1.5.74-git(SP-MOD)
API=1.3
ALGO=lyra2v2
GPUS=1
KHS=12843.89
ACC=16681
REJ=1
ACCMN=7.929
DIFF=8.000000
UPTIME=126225
TS=1450591594


Nicehash says:
Speed accepted: 13.9500
Speed rejected:  0.0000 (0.00%)
Diff:  8.00000000
Time (minutes): 2246


The difficulty seems to add up over time...

Regards



Am 18. Dezember 2015 23:49:00 MEZ, schrieb Stratehm 
<notifications@github.com>:

    Yes, correct.

    For the difficulty, unfortunately I do not see any problem in your
    log file.

        Also the difficulty is way off. Real 128 shown 20278476.371434607

    You see 20278476 in the Web client of the proxy and 128 on the
    Nicehash website, right ? What is the difficulty reported by your
    miner ?

    —
    Reply to this email directly or view it on GitHub
    <https://github.com/Stratehm/stratum-proxy/issues/62#issuecomment-165914419>.

**Comment by Stratehm** [comment]
I see... The Accepted difficulty field is not the actual pool difficulty. It is the cumulated difficulty accepted by the pool (so it indeed increases over time, each time you submit a valid share).

The current pool difficulty is displayed in the Pools page by the Difficulty field.

**Comment by coolinger** [comment]
Ok,  my fault! Thanks for fixing the hashrate display, very appreciated! 

Wish you a good time and a happy new year!
