### ISSUE TITLE
Error: Extranonce2 size is 3 (minimum is 4)

### ISSUE THREAD

**Issue by 9cat** [Stratehm/stratum-proxy#63]
Pool host:  
fail to verify when using nicehash connect to the proxy
Pool port:  
Pool user: ddd
Pool pass: dd
Algorithm: Scrypt

Resolving pool host  .. OK
Establishing connection with proxy... OK
Establishing connection with pool  ... OK
Sending mining.subscribe... OK
Sending mining.authorize... OK
Error: Extranonce2 size is 3 (minimum is 4).

**Comment by Stratehm** [comment]
You can change the "workerNumberLimit" option value to "1". It will no more consume the extranonce 2 size. The drawback is that only one worker will then be able to connect to the proxy at once.

**Comment by lucjager** [comment]
I still have the same issue with NiceHash,

This is the config i'm currently using:

{	
	"workerNumberLimit" : 1,
	"pools" : [ {
    "name" : "test pool",
    "host" : "sometestpool:3333",
    "user" : "testpoolbtcadres",
    "password" : "x",
    "enableExtranonceSubscribe" : true
  }]
}

**Comment by exitof1a** [comment]
Pool host:
My name is Efrain ( i need help)
fail to verify when using nicehash connect to the proxy
stratum+tcp://sha256.usa.nicehash.com:3334
User name: 1DXCfwfxGx57u9m6L772yGkQv3rzFnfbL3
password: efra

Resolving pool host .. OK
Establishing connection with proxy... OK
Establishing connection with pool ... OK
Sending mining.subscribe... OK
Sending mining.authorize... OK
Error: Extranonce2 size is 3 (minimum is 4).

**Comment by granatgas** [comment]
you can search "workerNumberLimit" in stratum-proxy-full-sample.conf and set to 1
