### ISSUE TITLE
I would like to commission a basic configurator

### ISSUE THREAD

**Issue by bladwig** [Stratehm/stratum-proxy#65]
I have a project I am working on and I would like to speak to you about possibly using your code in it. How can I go about contacting you regarding this? Your proxy is fantastic, btw. Thank you so much.

**Comment by Stratehm** [comment]
Please give me an e-mail address where I can contact you.

**Comment by bladwig** [comment]
You can reach me at bladwig@virtua-space.com.

Thank you. your product is fantastic and unbelievably stable. Thank you for your work.
