### ISSUE TITLE
"code": -32601, "message": "Procedure not found."

### ISSUE THREAD

**Issue by Jorropo** [Stratehm/stratum-proxy#82]
I try to use the proxy, I have add pools, configure proxy, ...
Here is my file configuration :
[stratum-proxy-minimal-sample.txt](https://github.com/Stratehm/stratum-proxy/files/1024179/stratum-proxy-minimal-sample.txt)
But ALL the pool say me that reponse :
[Pool-MinerGate XMR-Thread]:strat.mining.stratum.proxy.pool.PoolConnection - Pool-MinerGate XMR. JSON-RPC parsing error with line: {"jsonrpc": "2.0", "error": {"code": -32601, "message": "Procedure not found."}, "id": 1}
thx

**Comment by Jorropo** [comment]
I found solution (theorical not in code) remplace miner.subcribe by login

**Comment by FavyTeam** [comment]
I also get same errors when i use Monerogate, I would like to know how to fix these error ?

thx

**Comment by Jorropo** [comment]
@FavyTeam this is cause stratum proxy doesn't support xmr.

**Comment by FavyTeam** [comment]
@Jorropo thank you for your reply. But I run miner using "minerd -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45700 -u useremail -p x" and it works.

Have you got any idea ?
